name: Deploy to Digital Ocean

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn ci

      - name: Build application
        run: yarn start
        
      - name: Restart server application
        run: pm2 restart swgoh-counters-bot

          
