name: Deploy to Digital Ocean

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          
      - name: Build env variables
        run: |
          touch .env
          echo "${{ secrets.ENV }}" > .env
          touch src/setup/.firebase-config.js
          echo "${{ secrets.FIREBASE_CONFIG }}" > src/setup/.firebase-config.js
          touch src/setup/firebase-service-account.json
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT}}" > src/setup/firebase-service-account.json

      - name: Install dependencies
        run: yarn ci

      - name: Build application
        run: yarn start
        
      - name: Restart server application
        run: pm2 restart swgoh-counters-bot
